name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - 'yocto'
jobs:
      full-test:
        container:
	  image: btardio/runnerimg:assignment6-yocto
      runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh

